Meteor.subscribe 'ice_customer'
Meteor.subscribe 'ice_item'
Meteor.subscribe 'ice_order'
Meteor.subscribe 'ice_orderGroup'
Meteor.subscribe 'ice_payments'
Meteor.subscribe 'ice_userStaff'
Meteor.subscribe 'ice_staff'