Meteor.subscribe 'restuarant_order_table'
Meteor.subscribe 'restuarant_food_category'
Meteor.subscribe 'restuarant_product'
Meteor.subscribe 'restuarant_temp_product'
Meteor.subscribe 'restuarant_order_invoice'
